### ISSUE TITLE
Feature - Phone, Internet, or Both

### ISSUE THREAD

**Issue by Teddy-Weaver** [dsi-principles-prog/midterm-Teddy-Weaver#2]
Create a new feature that identifies whether the customer is subscribed to only phone, internet, or both services.

**Details**
Inputs: phone, internet
Expected Output: See below for details. Output should be a factor
- 'phone' - Only subscribes to phone, and not internet
- 'internet' - Only subscribes to internet service(s), and not phone.
  - if subscribed to multiple internet services (e.g. online security, online backup) but not phone, this should still be considered 'only internet'
- 'both' - Subscribed to both internet and phone services. 

**Testing**
Values should only contain 'phone', 'internet', or 'both'

**Comment by jcallahan510** [comment]
Function created with output 'phone' for phone-only subscribers, 'internet' for internet-only subscribers, and 'both' for subscribers of both phone internet service, in new column.

**Comment by jcallahan510** [comment]
Function created with output 'phone' for phone-only subscribers, 'internet' for internet-only subscribers, and 'both' for subscribers of both phone internet service, in new column.
